## Power meter: ORNO OR-WE-516 
#
# Modbus RTU (rs485)
#
# vars:
#
#   - modbus_controller_id
#   - power_meter_id
#   - power_meter_name
#
#VARS::
substitutions:
  modbus_controller_id: modbus_controller_id
  power_meter_id: power_meter_id
  power_meter_name: power_meter_name
  register_type: holding
  skip_updates: 5
  skip_updates_energy: 100
  force_new_range: true

<<: !include ../units.yaml 

sensor:
# ---------------------------- Phase voltage LN ------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_L1N
    name: "${power_meter_name}-L1N"
    force_new_range: ${force_new_range} 
    address: 0x000E
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_voltage}
    device_class: "voltage"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_L2N
    name: "${power_meter_name}-L2N"
    address: 0x0010
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_voltage}
    device_class: "voltage"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_L3N
    name: "${power_meter_name}-L3N"
    address: 0x0012
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_voltage}
    device_class: "voltage"
    state_class: "measurement"
# ---------------------------- Frequency -------------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_frequency
    name: "${power_meter_name}-Frequency"
    address: 0x0014
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_frequency}
    device_class: "frequency"
    state_class: "measurement"
# ---------------------------- Phase current ---------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_I1
    name: "${power_meter_name}-I1"
    address: 0x0016
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_current}
    device_class: "current"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_I2
    name: "${power_meter_name}-I2"
    address: 0x0018
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_current}
    device_class: "current"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_I3
    name: "${power_meter_name}-I3"
    address: 0x001A
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_current}
    device_class: "current"
    state_class: "measurement"
# ---------------------------- Active power ----------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_Ptotal
    name: "${power_meter_name}-Ptotal"
    address: 0x001C
    register_count: 8
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_power_active}
    device_class: "power"
    state_class: "measurement"
# ---------------------------- Reactive power --------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_Qtotal
    name: "${power_meter_name}-Qtotal"
    address: 0x0024
    register_count: 8
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_power_reactive}
    device_class: "reactive_power"
    state_class: "measurement"
# ---------------------------- Apparent power --------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_Stotal
    name: "${power_meter_name}-Stotal"
    address: 0x002C
    register_count: 8
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    unit_of_measurement: ${unit_power_apparent}
    device_class: "apparent_power"
    state_class: "measurement"
# ---------------------------- PowerFactor -----------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    id: ${power_meter_id}_system_PF
    name: "${power_meter_name}-PF"
    address: 0x0034
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_apparent}
    device_class: "apparent_power"
    state_class: "measurement"