## Power meter: ORNO OR-WE-516 
#
# Modbus RTU (rs485)
#
# vars:
#
#   - modbus_controller_id
#   - power_meter_id
#   - power_meter_name
#
#VARS::
substitutions:
  modbus_controller_id_2: modbus_controller_id
  power_meter_id_2: power_meter_id
  power_meter_name_2: power_meter_name
  register_type_2: holding
#  skip_updates_2: 600
#  force_new_range_2: true

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_SerialNumber
    name: "${power_meter_name_2}-SerialNumber"
    address: 0x0000
    register_type: ${register_type_2}
    value_type: U_DWORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_MeterID
    name: "${power_meter_name_2}-MeterID"
    address: 0x0002
    register_type: ${register_type_2}
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Baudrate
    name: "${power_meter_name_2}-Baudrate"
    address: 0x0003
    register_type: ${register_type_2}
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Software
    name: "${power_meter_name_2}-Software"
    address: 0x0004
    register_type: ${register_type_2}
    value_type: FP32
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Hardware
    name: "${power_meter_name_2}-Hardware"
    address: 0x0006
    register_type: ${register_type_2}
    value_type: FP32
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_CT_Rate
    name: "${power_meter_name_2}-CT_Rate"
    address: 0x0008
    register_type: ${register_type_2}
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_S0_Rate
    name: "${power_meter_name_2}-S0_Rate"
    address: 0x0009
    register_type: ${register_type_2}
    value_type: FP32
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_A3
    name: "${power_meter_name_2}-A3"
    address: 0x000B
    register_count: 2
    register_type: ${register_type_2}
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_CycleTime
    name: "${power_meter_name_2}-CycleTime"
    address: 0x000D
    register_type: ${register_type_2}
    value_type: U_WORD
